name: web_lms
description: CMS LMS

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  pull_to_refresh: ^2.0.0
  dio: ^4.0.0
  retrofit: any
  pretty_dio_logger: ^1.2.0-beta-1
  flutter_typeahead: ^3.2.1
  intl: ^0.17.0
  shared_preferences: ^2.0.8
  image_picker: ^0.8.4+4
  flutter_svg: ^0.23.0+1
  file_picker: ^4.2.3
  url_launcher: ^6.0.13
  excel: ^2.0.0-null-safety-3

  path_provider_windows: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.0.0+1
  build_runner: ^2.0.4
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/

